### ISSUE TITLE
will you add support for criware ps vita?

### ISSUE THREAD

**Issue by 0xh3LL0** [HaselLoyance/criware-tools#1]
just as the title says...

**Comment by yar-sh** [comment]
At this moment I have had zero experience with Criware games for PS Vita, so I can't even say how much different it is from PSP. 

For right now I'll leave it for PSP only, but if there is future interest/demand for it, then I'll look into PS Vita.

**Comment by 0xh3LL0** [comment]
thank you for reply, i'll just wait then.

but just in case you're interested, maybe you can take a look at this
https://github.com/CommitteeOfZero/SciAdv.Net
its incomplete though (rather that incomplete, looks like the author didnt upload all the code on purpose)

**Comment by yar-sh** [comment]
I know that CoZ developed that tool for desktop versions of games. It works on PS Vita?

I've used this tool initially to extract English translation from S;G on Steam, but I haven't done any text insertion (though I think that the program supports it). I'm not sure what else you would want to do with it

**Comment by 0xh3LL0** [comment]
> It works on PS Vita?

at least on the game i try working on, yes... its oregairu

> I'm not sure what else you would want to do with it

those project didnt even build for me, so i'm looking for alternative
i found [chaos child script decompiler](https://github.com/hatsuyuki15/chaos-child-script-decompiler) which is also based on SciAdv.Net but its only decompiler,
so i'm looking for working script decompiler/compiler, though every game have different character map and i need to map the character manually, thats something i can do by myself.

**Comment by yar-sh** [comment]
Yeah, I'm not sure I can pack the scx scripts that PS Vita/PC version use. Your best bet is to contact CoZ directly, but I have no idea if they will be that open about their behind-the-scenes work

**Comment by 0xh3LL0** [comment]
i guess, there is no choice then...
